# Generated by Django 4.2.7 on 2026-03-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=18, help_text='User must be 18+ to use this app'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age_verified',
            field=models.BooleanField(default=False, help_text='Confirms user is 18+'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Stored for age verification', null=True),
        ),
    ]
