# Generated by Django 4.2.7 on 2026-04-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_novelty_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aireply',
            new_name='accounts_ai_user_id_7c3843_idx',
            old_name='accounts_ai_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aireply',
            new_name='accounts_ai_expires_1ced78_idx',
            old_name='accounts_ai_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='aireply',
            new_name='accounts_ai_fingerp_def511_idx',
            old_name='accounts_ai_fingerprint_idx',
        ),
        migrations.RenameIndex(
            model_name='aireply',
            new_name='accounts_ai_normali_d788cf_idx',
            old_name='accounts_ai_normalized_idx',
        ),
        migrations.AddIndex(
            model_name='aireply',
            index=models.Index(fields=['embedding'], name='accounts_ai_embeddi_f2f41e_idx'),
        ),
    ]
