# Generated by Django 4.2.7 on 2026-04-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_accounts_ai_user_id_created_idx_accounts_ai_user_id_7c3843_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aireply',
            name='accounts_ai_embeddi_f2f41e_idx',
        ),
    ]
