# Generated by Django 4.2.7 on 2026-04-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
        ('accounts', '0006_user_email_unique'),
    ]

    operations = [
    ]
