# Generated by Django 4.2.7 on 2026-04-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0005_alter_user_email_0006_user_email_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_count', models.IntegerField(default=0)),
                ('last_question_starter', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VocabCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
                ('last_used_reply', models.IntegerField()),
            ],
            options={
                'unique_together': {('user_id', 'word')},
            },
        ),
        migrations.CreateModel(
            name='NgramLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('ngram', models.CharField(max_length=200)),
                ('ngram_type', models.CharField(choices=[('bigram', 'Bigram'), ('trigram', 'Trigram')], max_length=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'ngram'], name='accounts_ng_user_id_619b35_idx'), models.Index(fields=['used_at'], name='accounts_ng_used_at_22bb4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_number', models.IntegerField()),
                ('response_text', models.TextField()),
                ('structure_used', models.CharField(max_length=1)),
                ('tone_used', models.CharField(max_length=20)),
                ('question_starter', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.conversationlog')),
            ],
            options={
                'ordering': ['reply_number'],
                'unique_together': {('conversation', 'reply_number')},
            },
        ),
    ]
