# Generated by Django 4.2.7 on 2026-05-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_conversationlog_vocabcooldown_ngramlog_responselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireply',
            name='button_intent',
            field=models.CharField(blank=True, help_text="Button name if intent_type='button' (e.g., 'morning_flirt', 'sensual')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aireply',
            name='conversation_context',
            field=models.TextField(blank=True, help_text='Original pasted conversation (LEFT side)', null=True),
        ),
        migrations.AddField(
            model_name='aireply',
            name='intent_type',
            field=models.CharField(blank=True, choices=[('specific', 'Specific'), ('button', 'Button')], help_text='Whether response was generated from pasted conversation (specific) or button click (button)', max_length=10, null=True),
        ),
    ]
