# Generated by Django 4.2.7 on 2026-06-27 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_delete_dead_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks_used', models.PositiveIntegerField(default=0)),
                ('referral_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('low_clicks_notified', models.BooleanField(default=False)),
                ('out_of_clicks_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credits',
                'verbose_name_plural': 'User Credits',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clicks_granted', models.PositiveIntegerField()),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('welcome', 'Welcome'), ('low_clicks', 'Low Clicks'), ('out_of_clicks', 'Out of Clicks'), ('referral_joined', 'Referral Joined'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='accounts_no_user_id_b29cd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('welcome', 'Welcome bonus'), ('referral', 'Referral bonus'), ('purchase', 'Purchase'), ('admin', 'Admin adjustment')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = never expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_credits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='accounts.usercredits')),
            ],
            options={
                'indexes': [models.Index(fields=['user_credits', 'expires_at'], name='accounts_cr_user_cr_f98446_idx')],
            },
        ),
    ]
