# Generated by Django 4.2.7 on 2026-06-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usercredits_payment_notification_creditgrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Premium Email',
                'verbose_name_plural': 'Premium Emails',
            },
        ),
        migrations.AddField(
            model_name='usercredits',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
