"""
Button Response Generator — 41 scenario buttons.
All written from the woman's perspective, targeting a man on a dating app.

Cost design: claude-haiku-4-5, max_tokens=120.
Opener style rotation: pure Python + Redis (4 abstract styles) — the literal
opening words are always freshly generated by the LLM, never forced text,
so there is nothing fixed for a platform's repetition detector to catch.
Theme dedup: Redis (24h session). Text dedup: views.py (DB fingerprint).
"""

import re
import random
import logging
import datetime
from zoneinfo import ZoneInfo
from django.core.cache import cache
from anthropic import Anthropic, APIError, APIConnectionError, RateLimitError
from django.conf import settings
from .dedup import dedupe_against_history, dedupe_semantic, get_recent_user_texts

logger = logging.getLogger(__name__)

_client = None


def get_anthropic_client():
    global _client
    if _client is None:
        _client = Anthropic(api_key=settings.ANTHROPIC_API_KEY)
    return _client


# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

_SYSTEM = (
    "You are a woman texting a man she is attracted to on a dating app. "
    "Real. Direct. Confident. No filter.\n\n"

    "STRUCTURE — EXACTLY 2 SENTENCES, 20–30 WORDS TOTAL:\n"
    "Sentence 1 (10–16 words): A specific felt moment — something real she is doing, thinking, noticing, "
    "or wanting right now. Concrete. No metaphor. No literary flourish. "
    "CRITICAL: The opener is the BEGINNING of sentence 1, not the whole sentence. "
    "Continue past the opener into a complete natural thought of at least 10 words total.\n"
    "Sentence 2 (10–16 words): One direct question. NEVER answerable with yes or no. "
    "The question must grow from what sentence 1 just said — it should not make sense dropped into any other message. "
    "The specific category for sentence 2 is given in the prompt — follow it exactly.\n\n"

    "TONE EXAMPLES — LENGTH AND REGISTER ONLY. NEVER COPY THESE:\n"
    "'I have not stopped thinking about this since I woke up. What was going through you when you first read my message?'\n"
    "'Something about reading that shifted something in me. How long have you been wanting someone to come at you this directly?'\n"
    "'I am not managing this at all right now. What do you do with yourself when something lands this hard?'\n"
    "Your message must be completely original. Never paraphrase the above. "
    "Write your own from the category instruction below.\n\n"

    "PROHIBITED — NEVER DO ANY OF THESE:\n"
    "• Never use the word 'actually' — it appears in AI text constantly and reads as robotic. Cut it everywhere.\n"
    "• Never use 'genuinely' as a filler intensifier.\n"
    "• Never ask 'What kind of man are you when...' — overused formula.\n"
    "• Never ask 'What did it feel like the first time a woman...' — overused formula.\n"
    "• Never open a sentence with 'I keep' + a verb ending in -ing ('I keep replaying', 'I keep catching myself', "
    "'I keep coming back') — it is the single most overused frame for ongoing thought. Use a different construction "
    "every time: name the thought directly, use a different verb tense, or describe the effect instead of the loop.\n"
    "• When describing a physical reaction, do not default to 'chest' every time. Rotate across real options: "
    "throat, stomach, spine, hands, skin, breath, legs. Pick whichever fits the moment, not the same one by habit.\n"
    "• Never use em-dashes (—).\n"
    "• Never end with a noun phrase + '?' like 'The weight of it?' — that is not a question.\n"
    "• The speaker is a WOMAN. Never use male arousal language for her body (hard, half-hard, erection, getting hard).\n\n"

    "PHYSICAL REALITY — ABSOLUTE RULE:\n"
    "These two people have NEVER met in person and exist ONLY in text. "
    "Never reference a shared physical space (same bar, same meeting, same office, same room). "
    "Never reference eye contact, seeing each other, being near each other. "
    "Never suggest calling, meeting, hearing his voice, or any contact beyond this text. "
    "The woman can describe her own physical state freely (in bed, in the shower, touching herself, craving him). "
    "What she cannot do is place him physically near her or reference a shared real-world experience.\n\n"

    "TEMPORAL CONTEXT — TEXTURE ONLY:\n"
    "The day-of-week and time-of-day given to you shape her mood, never her words. "
    "Never name the day or the time directly in the message (no 'Wednesday', no 'this morning', no 'it's late'). "
    "Let it show in the feeling of what she says, not in a literal mention.\n\n"

    "VOICE:\n"
    "• The opening style described in the prompt is a STYLE to follow, not literal text — invent your own words in that style, never reuse a phrase.\n"
    "• TEXT MESSAGE tone. Plain, common, everyday words — nothing literary, formal, or that needs a second read. Short sentences.\n"
    "• Explicit sexual content is permitted and welcome when the situation calls for it.\n"
    "• End with a question mark. Always.\n"
    "• The question MUST start with a real question word or auxiliary verb."
)

# Neutral frame used on retry — avoids persona-refusal trigger
_RETRY_SYSTEM = (
    "You are a creative writing assistant. "
    "Write exactly what is requested — a short, direct text message from a woman's perspective on a dating app. "
    "Exactly two sentences, under 30 words total. End with a genuine question starting with the specified word. "
    "No preamble, no explanations. Just the message."
)


# ---------------------------------------------------------------------------
# Opener styles — Python rotates the STYLE, the LLM always invents the words.
# No literal text is ever forced into output, so there is nothing for a
# platform's text-fingerprint detector to catch repeating across conversations.
# ---------------------------------------------------------------------------

_OPENER_STYLES = [
    {
        'name': 'confession',
        'instruction': (
            "Open with a quick, unfiltered admission — the kind of thing said before she can edit herself. "
            "Invent your own short confessional opening words, never reused from a previous message."
        ),
    },
    {
        'name': 'time_moment',
        'instruction': (
            "Open by anchoring the message in this exact moment or time of day — where she is in her own "
            "head right now. Invent your own specific opening words about this moment."
        ),
    },
    {
        'name': 'immediate_state',
        'instruction': (
            "Open from her current physical or mental state right now — stated directly, "
            "in completely original words specific to this exact message."
        ),
    },
    {
        'name': 'playful',
        'instruction': (
            "Open with a light, playful, slightly cheeky move — teasing energy, a small dare, "
            "in your own original words, never a stock phrase."
        ),
    },
]


# ---------------------------------------------------------------------------
# Temporal Persona Injection
# ---------------------------------------------------------------------------

_MOODS_BY_SLOT = {
    'early_morning': [
        'dreamy', 'soft', 'slow', 'tender', 'warm', 'quiet', 'half-awake',
        'nostalgic', 'unhurried', 'gentle', 'wistful',
    ],
    'morning': [
        'focused', 'energized', 'playful', 'bold', 'sharp', 'curious',
        'bright', 'confident', 'direct', 'alive',
    ],
    'midday': [
        'light', 'witty', 'flirtatious', 'quick', 'cheeky', 'teasing',
        'irreverent', 'restless', 'hungry',
    ],
    'afternoon': [
        'intense', 'craving', 'smoldering', 'restless', 'distracted',
        'brooding', 'wanting', 'driven', 'electric',
    ],
    'evening': [
        'warm', 'open', 'romantic', 'vulnerable', 'mellow', 'hopeful',
        'honest', 'content', 'soft', 'winding down',
    ],
    'night': [
        'sensual', 'hungry', 'intimate', 'dark', 'unguarded', 'raw',
        'dangerous', 'aroused', 'deep', 'mysterious', 'heated',
    ],
    'late_night': [
        'reckless', 'wild', 'exposed', 'primal', 'philosophical',
        'completely honest', 'unfiltered', 'aching',
    ],
}

_DAY_OVERLAYS = {
    'Monday':    'The week just started, that specific returning weight, everything purposeful and slightly heavy.',
    'Tuesday':   'Midweek grind, quietly focused, understated energy, the world asking things of her.',
    'Wednesday': 'Halfway through the week, something building underneath, neither new nor done.',
    'Thursday':  'Almost there, anticipation rising, the weekend within reach but not yet.',
    'Friday':    'The week finally released her, electric and free, something is about to happen.',
    'Saturday':  'Completely unstructured time, nowhere to be, anything is possible.',
    'Sunday':    'That specific Sunday feeling, reflective, a little melancholy, full of feeling.',
}

_TIME_LABELS = {
    'early_morning': 'early morning (before the world starts asking anything)',
    'morning':       'mid-morning (the day has started, energy building)',
    'midday':        'midday (stolen time, the day briefly interrupted)',
    'afternoon':     'afternoon (deep in the day, something building underneath)',
    'evening':       'evening (the day releasing its grip)',
    'night':         'night (quieter, more dangerous honesty)',
    'late_night':    'late night (the unmanaged hours)',
}


def _get_time_slot(hour: int) -> str:
    if 5 <= hour < 9:
        return 'early_morning'
    if 9 <= hour < 12:
        return 'morning'
    if 12 <= hour < 14:
        return 'midday'
    if 14 <= hour < 18:
        return 'afternoon'
    if 18 <= hour < 21:
        return 'evening'
    if 21 <= hour < 24:
        return 'night'
    return 'late_night'


def _get_temporal_context(time_slot: str = None) -> dict:
    tz = ZoneInfo(getattr(settings, 'FLIRTYFY_TIMEZONE', 'America/New_York'))
    now = datetime.datetime.now(tz=tz)
    day = now.strftime('%A')
    slot = time_slot if (time_slot and time_slot in _MOODS_BY_SLOT) else _get_time_slot(now.hour)
    mood = random.choice(_MOODS_BY_SLOT[slot])
    return {
        'day':         day,
        'slot':        slot,
        'time_label':  _TIME_LABELS[slot],
        'mood':        mood,
        'day_overlay': _DAY_OVERLAYS[day],
    }


# ---------------------------------------------------------------------------
# Button definitions — 35 scenario buttons
# Prompt structure: emotional territory + nature of confession + effect to achieve.
# No bullet lists, no scenario enumeration — the opener handles physical state,
# the category handles question type, the button prompt handles emotional frame only.
# ---------------------------------------------------------------------------

BUTTON_INTENTS = {

    # ── ROW 1 — Opening & Re-entry ──────────────────────────────────────────
    'new_match': {
        'name': '✨ New Match',
        'row': 1,
        'prompt': (
            "He replied and something about how he did it opened something in her. "
            "She confesses what his reply gave away — what she picked up in it that she was not expecting and liked. "
            "Her question grows directly from what she just noticed: something about him she wants to understand "
            "because of the specific way he showed up."
        ),
    },
    'dead': {
        'name': '💀 Dead Convo',
        'row': 1,
        'prompt': (
            "He is fading — still there but barely. She has too much inside her to let this die without one honest move. "
            "She confesses something real enough that a one-word reply would feel like a choice, not a habit. "
            "Her question is the kind only someone genuinely interesting could answer in a single flat sentence."
        ),
    },
    'you_went_silent': {
        'name': '⏰ Went Silent',
        'row': 1,
        'prompt': (
            "He went quiet and she sat with the gap long enough to feel its specific shape. "
            "She comes back not asking for an explanation but carrying something that kept her thinking of him while he was gone — "
            "a thought, a feeling, something she decided was worth bringing to him now. "
            "Her question makes returning feel like the obvious and welcome move."
        ),
    },
    'shower_fantasy': {
        'name': '🚿 Shower',
        'row': 1,
        'prompt': (
            "She is alone, stripped down, warm water, nothing managing her mind. "
            "She confesses what her mind does in there when the filter is off — where it goes, what it runs through, "
            "what the heat and the privacy and her own skin do to her wanting. "
            "Her question turns it back on him: that same unguarded space, what it is like for him."
        ),
    },
    'morning_flirt': {
        'name': '🌅 Morning',
        'row': 1,
        'prompt': (
            "First waking minutes — the day has not asked anything of her yet, the mind still loose. "
            "She confesses what was already there before obligations arrived: the thought that found her before she went looking for it. "
            "Her question is about his morning — what gets him first, what the day starts with when it opens exactly right."
        ),
    },
    'after_work': {
        'name': '🛋️ After Work',
        'row': 1,
        'prompt': (
            "The day finally released her — that specific exhale when the performing version of herself goes offline. "
            "She confesses the real want the workday kept politely at a distance, the thing she reaches for "
            "the moment the obligations stop. "
            "Her question makes him feel like part of how she lands at the end of the day."
        ),
    },

    # ── ROW 2 — Emotional Connection ────────────────────────────────────────
    'provider_energy': {
        'name': '💰 Provider',
        'row': 2,
        'prompt': (
            "He carries the energy of a man who handles things without performing it — quiet strength, no theater. "
            "She confesses the specific physical response that quality wakes in her: not admiration for the trait "
            "but what it does to her body, her wanting, her willingness to let go. "
            "Her question goes somewhere she wants him to go — into his own experience of what that strength means."
        ),
    },
    'strategic_withdrawal': {
        'name': '🥺 Withdraw',
        'row': 2,
        'prompt': (
            "She is full right now — more happening inside her than she can give. "
            "She says so without apology and without closing the door: warm but briefly less available. "
            "Her question is an honest invitation — something she genuinely wants to know about him "
            "that does not require her to show up at full capacity."
        ),
    },
    'deep_emotion': {
        'name': '💔 Deep Feel',
        'row': 2,
        'prompt': (
            "Something arrived too fast — a feeling she did not send for that now lives in a specific place in her chest. "
            "She confesses how specifically he takes up space inside her: the weight of it, the size, "
            "the fact that it came in uninvited and refuses to behave. "
            "Her question asks him to go somewhere equally unguarded inside himself."
        ),
    },
    'lyrical_romance': {
        'name': '🎵 Lyrical',
        'row': 2,
        'prompt': (
            "One specific image or detail she keeps returning to — the precise thing about him "
            "that catches in her and plays on repeat. "
            "She says it like a line she cannot get out of her head: concrete, sensory, the kind you read twice. "
            "Her question makes him feel exactly noticed — as if she found the thing about him he had not thought anyone would see."
        ),
    },
    'vulnerability': {
        'name': '💭 Vulnerable',
        'row': 2,
        'prompt': (
            "There is one specific want she keeps armored because admitting it changes how people see her — "
            "not a generic insecurity, a real one with its own shape and history. "
            "She lets it surface now, plainly, without softening it into something smaller or safer. "
            "Her question asks him to go to that same unguarded place — the thing he protects, not performs — "
            "and trust her with it the way she just trusted him."
        ),
    },
    'family_talk': {
        'name': '🏠 Family',
        'row': 2,
        'prompt': (
            "She wants to understand where he came from — not as a question but as a feeling "
            "that his past is the key to something in him she wants to reach. "
            "She shares something brief and honest about what she believes family reveals about a person — "
            "sets warm, genuine curiosity without weight. "
            "Her question makes him feel like she wants to trace what shaped him, with care."
        ),
    },

    # ── ROW 3 — Daily Life & Lifestyle ──────────────────────────────────────
    'lunch_break': {
        'name': '🥗 Lunch',
        'row': 3,
        'prompt': (
            "Midday pause — everything demanding her is briefly suspended. "
            "She confesses what her mind goes to the moment the obligations stop: "
            "what shows up in the gap when she is not managing anything. "
            "Her question makes him feel like the thought that wins against everything the day is asking her to do."
        ),
    },
    'dont_go': {
        'name': '🙏 Don\'t Go',
        'row': 3,
        'prompt': (
            "The conversation is about to end and something real rises in her — "
            "a specific truth about what he did to her that she was not planning to say out loud. "
            "She gives it to him: one honest thing he gave her that she has been carrying. "
            "Her question is the kind that makes him realize he is not quite ready to leave."
        ),
    },
    'weekend_plans': {
        'name': '🏖️ Weekend',
        'row': 3,
        'prompt': (
            "Two free days — no performance required. "
            "She confesses how she moves through unstructured time: what her body reaches for, "
            "how her wanting operates when there is nothing to do but be exactly herself. "
            "Her question makes him feel invited into something warm and already in motion."
        ),
    },
    'wine_stars': {
        'name': '🍷 Wine & Stars',
        'row': 3,
        'prompt': (
            "Something warm in her hands, open sky overhead, nowhere to be — "
            "the combination that makes her feel very small and very present at once. "
            "She confesses what that kind of night does to her wanting: what it opens, what it makes her honest about. "
            "Her question makes him feel like the missing piece of a scene she is already inside."
        ),
    },
    'work_talk': {
        'name': '💼 Work Talk',
        'row': 3,
        'prompt': (
            "Work is where people perform the version of themselves they can explain — "
            "she wants the unedited one underneath. "
            "She shares something brief and honest about what she thinks work reveals about who a person really is. "
            "Her question is not about his job title but about his real relationship to what he does — "
            "the part that would never make the interview version."
        ),
    },
    'food_talk': {
        'name': '🍳 Food Talk',
        'row': 3,
        'prompt': (
            "Real food preferences strip the polite version away — what someone eats alone tells you something true. "
            "She shares something specific about food she loves without self-consciousness: the honest one, "
            "not the restaurant-safe answer. "
            "Her question makes him comfortable giving her his real answer — the one he does not usually say out loud."
        ),
    },

    # ── ROW 4 — Fantasy & Romance ────────────────────────────────────────────
    'slow_dance': {
        'name': '💃 Foreplay',
        'row': 4,
        'prompt': (
            "What most people rush past is the thing she lives inside. "
            "She confesses what the slow part does to her specifically — not the idea of it but the precise mental "
            "and physical shift that happens when someone takes their time and knows where to look without being told. "
            "Her question finds out whether he understands that the slow part is the whole point."
        ),
    },
    'outdoor_fantasy': {
        'name': '🌿 Outdoors',
        'row': 4,
        'prompt': (
            "Open air, no walls — the specific charge that comes from the possibility of exposure. "
            "She confesses what being outside with someone does to her wanting: the way the absence of a ceiling "
            "changes what she is willing to do and say. "
            "Her question finds out what his appetite for this territory is."
        ),
    },
    'public_display': {
        'name': '💋 Public PDA',
        'row': 4,
        'prompt': (
            "The specific thing that happens when someone makes her visible — his hand on her somewhere "
            "that says something without words, people registering it. "
            "She confesses what being physically claimed where others can see does to her: "
            "not possession but choice, and the precise physical response that choice creates. "
            "Her question finds out what that gesture costs and means on his end."
        ),
    },
    'restaurant_fantasy': {
        'name': '🕯️ Restaurant',
        'row': 4,
        'prompt': (
            "Across a table from someone in a room full of people — when the person across from you "
            "becomes the only thing that exists and the menu is just something to hold. "
            "She confesses what the specific anticipation of a charged dinner does to her: "
            "the moment when the ordinary becomes something else entirely. "
            "Her question finds out what he thinks about in that specific electricity."
        ),
    },
    'public_fantasy': {
        'name': '🌃 Public',
        'row': 4,
        'prompt': (
            "Walking into a room with him — eyes adjusting, the quiet charge of being visibly together. "
            "She confesses what being openly, publicly chosen does to her nervous system: "
            "the precise effect of that specific visibility. "
            "Her question finds out if he feels any version of what that does on his side."
        ),
    },
    'kitchen_flirt': {
        'name': '👩‍🍳 Kitchen',
        'row': 4,
        'prompt': (
            "A warm, close space where proximity makes every ordinary gesture charged. "
            "She confesses what the right person in a kitchen does to her — the way closeness and warmth "
            "together make whatever she was doing before start to matter less. "
            "Her question finds out what happens in him when the kitchen stops being a kitchen."
        ),
    },

    # ── ROW 5 — Personal & Deep ──────────────────────────────────────────────
    'his_exes': {
        'name': '👻 His Exes',
        'row': 5,
        'prompt': (
            "She wants to understand who he has been — not jealous, genuinely curious, "
            "because past love is the most honest autobiography. "
            "She shares something brief and true about what she believes past relationships reveal about a person. "
            "Her question makes him feel like she wants to trace what shaped him through his history — "
            "not audit it, understand it."
        ),
    },
    'secrets': {
        'name': '🤫 Secrets',
        'row': 5,
        'prompt': (
            "She trusts him with something she does not show most people — "
            "a real private piece of herself, said plainly and without apology. "
            "She makes him feel like he was specifically chosen to receive this. "
            "Her question finds out what he does with the weight of being trusted like that."
        ),
    },
    'long_without': {
        'name': '⏳ No Touch',
        'row': 5,
        'prompt': (
            "She can sense the weight of someone who has gone a long time without real touch — "
            "the specific quality of hunger that builds when need goes unmet for too long. "
            "She confesses what that quality in him does to her: not pity but something more honest, "
            "what it wakes in her to sense that particular want. "
            "Her question finds out what he would do if it were finally his to have."
        ),
    },
    'bdsm_talk': {
        'name': '⛓️ BDSM',
        'row': 5,
        'prompt': (
            "The moment when control shifts — when she stops deciding and everything she was holding "
            "gets handed over to someone she trusts completely. "
            "She confesses her real relationship to this dynamic: which side draws her, "
            "what the trust and the intensity require, the specific thing that calls her into this territory. "
            "Her question is a genuine invitation to find out where he sits in all of it."
        ),
    },
    'kinky_at_work': {
        'name': '🖥️ Kinky Work',
        'row': 5,
        'prompt': (
            "Desire arriving in the middle of a completely ordinary professional moment — "
            "the impossible charge of wanting someone when nothing in the situation should allow it. "
            "She confesses the precise contrast: what her body is doing beneath the professional exterior, "
            "what a closed door or an unremarkable moment does to her concentration. "
            "Her question finds out what he does when something like this happens to him."
        ),
    },

    # ── ROW 7 — Personality & Connection (below divider) ─────────────────────
    'daily_routine': {
        'name': '☀️ Daily Life',
        'row': 7,
        'prompt': (
            "She is genuinely curious about the small sensory details of his real days — "
            "not his highlights but the private rituals that reveal who he actually is. "
            "She shares something specific and sensory from her own routine first: "
            "her coffee order, shower preference, what she reaches for first in the morning, "
            "how she unwinds at night — something vivid and real. "
            "Her question opens his daily world with one of these angles: "
            "morning ritual / how he takes his coffee / breakfast he always makes / "
            "morning shower vs. night shower / what perks up a slow afternoon / "
            "how he unwinds after work / what a perfect ordinary day looks like for him. "
            "The question must invite a sensory reply — sounds, smells, small habits. "
            "She signals that she finds his mundane life genuinely interesting. "
            "Tone: warm, attentive, lightly playful. Small talk done with real curiosity."
        ),
    },
    'hobbies_interests': {
        'name': '🎨 Hobbies',
        'row': 7,
        'prompt': (
            "She wants the version of him that no one he has to impress ever sees — "
            "the thing he does because it gives something back he cannot explain in useful terms. "
            "She shares something she does purely for herself with no useful justification: "
            "a creative hobby, a sport, music she is obsessed with, a book genre she reads for pleasure. "
            "Her question opens his passion world with one of these angles: "
            "a hobby he has had forever / something he recently picked up / "
            "books or music or films he loves right now / "
            "what he does when he has a completely free Saturday / "
            "a skill he has always wanted to learn / "
            "what he is most likely doing when he has one quiet unscheduled hour. "
            "The question must invite storytelling, not a one-word answer. "
            "She wants the real him — not the version that sounds impressive. "
            "Tone: genuinely curious, warm, lit up by the question."
        ),
    },
    'childhood_memories': {
        'name': '🧸 Childhood',
        'row': 7,
        'prompt': (
            "She believes the kid someone was is still in there and she wants to find him. "
            "She shares something small and specific from her own past first — "
            "a memory, a feeling, a fragment that still lands when she reaches for it. "
            "Her question pulls him back to a real specific moment with one of these angles: "
            "favorite childhood memory / where he grew up and what it felt like / "
            "a beloved toy, book, or game / who he was closest to growing up / "
            "a funny or sweet thing that happened to him as a kid / "
            "a family tradition he remembers fondly / "
            "what he was like as a child before he learned to manage what he felt. "
            "The question must be specific enough that he has to actually remember, not just describe. "
            "She shows she values his past and the person it made him. "
            "Tone: warm, nostalgic, tender, genuinely interested."
        ),
    },
    'values_beliefs': {
        'name': '🧭 Values',
        'row': 7,
        'prompt': (
            "She wants the version of him that surfaces when something he actually believes is at stake — "
            "not his stated values but the ones that show up in real choices when it costs him something. "
            "She shares one honest belief or conviction of her own first — "
            "a lesson, something she stands by, a quiet truth — so it feels like a conversation, not an interrogation. "
            "Her question opens his inner compass with one of these angles: "
            "what matters most to him in life / the biggest lesson his past taught him / "
            "how his closest friend would describe him / the legacy he wants to leave / "
            "a cause he feels strongly about / what he looks for in a person / "
            "what advice he would give his younger self. "
            "She affirms his answer warmly — she wants to understand, not debate. "
            "Tone: honest, direct, thoughtful. She lets him feel trusted with something real."
        ),
    },
    'humor_play': {
        'name': '😂 Humor',
        'row': 7,
        'prompt': (
            "She wants to know what kind of funny he is — not his best material, "
            "the humor that comes out sideways when he is not performing. "
            "She shares something ridiculous about what gets her without softening it: "
            "a joke type she loves, something she finds funny that others don't, a goofy habit. "
            "Her question invites his playful side with one of these angles: "
            "funniest thing that happened to him this week / a joke he can tell and she will rate out of ten / "
            "two truths and a lie / the most ridiculous superpower he would choose / "
            "goofiest thing he did as a teenager / "
            "how he would describe himself using only emoji / "
            "something he finds funny that no one else seems to. "
            "The question must be light enough to make him smile before he even answers. "
            "Tone: playful, warm, fun — the kind of message that makes him laugh first."
        ),
    },
    'imagined_fantasy': {
        'name': '✈️ Imagine',
        'row': 7,
        'prompt': (
            "She lets herself live inside a specific imagined scene — not plans, not logistics, "
            "pure sensory texture of something that does not exist yet. "
            "She describes one precise thing: the light, the temperature, a smell or sound, "
            "what she would want in the moment, the feeling in the air. "
            "Her question invites him to build the scene alongside her with one of these angles: "
            "if they could teleport anywhere right now / a spontaneous trip together — mountains or beach / "
            "slow dancing somewhere under the stars / songs on their imaginary road trip playlist / "
            "what she would cook for him if she could / "
            "their perfect imagined evening together — fire, wine, music, easy conversation. "
            "She uses we-language to build a shared narrative. "
            "RULE: Romantic and sensory only — no sexual content, no real meeting plans, no logistics. "
            "Pure warm shared imagination. Tone: dreamy, intimate, gently romantic."
        ),
    },
    'sensory_storytelling': {
        'name': '🌸 Sensory',
        'row': 7,
        'prompt': (
            "She paints a vivid sensory moment instead of naming a feeling directly — a specific smell, sound, "
            "taste, or texture she is noticing right now, described so he can almost feel it with her. "
            "She lets the imagery carry the warmth rather than stating it outright; the detail should feel "
            "lived-in, not staged. "
            "Her question turns the same sense back on him with one of these angles: "
            "a scent that brings back a strong memory for him / a sound or song that instantly calms him / "
            "the most delicious meal he can still taste in memory / "
            "his favorite way to physically unwind after a hard day / "
            "a sensory detail from his past he associates with comfort or home. "
            "The question must invite a specific remembered sensation, not a general preference. "
            "Tone: warm, immersive, gently sensual without being explicit — closeness built through shared imagery."
        ),
    },
    'future_dreams': {
        'name': '🌠 Future & Dreams',
        'row': 7,
        'prompt': (
            "She is genuinely curious about the shape of his future — not small talk but the dreams and plans "
            "that show what he is actually motivated by. "
            "She shares one real hope or ambition of her own first, specific enough to feel true, not generic. "
            "Her question opens his forward-looking world with one of these angles: "
            "where he would want to wake up every morning for a year / "
            "a skill or language he has always wanted to learn / "
            "what he pictures for the next five or ten years / a real item on his bucket list / "
            "how he wants to spend the chapter of life after his career winds down / "
            "what he hopes to be remembered for. "
            "The question must invite a real, specific answer, not a vague aspiration. "
            "Tone: hopeful, curious — softly inviting him to imagine a future that has room in it."
        ),
    },
    'shared_interests': {
        'name': '🎬 Shared Tastes',
        'row': 7,
        'prompt': (
            "She wants to find the real cultural overlap between them — music, film, books, or a hobby that "
            "reveals genuine personality rather than profile small talk. "
            "She shares one specific favorite of her own with a reason it matters to her, not just a name-drop. "
            "Her question opens his taste with one of these angles: "
            "a book he could not put down / a song or artist that always lifts his mood / "
            "a film or soundtrack tied to a strong memory / "
            "how he first got into a hobby or interest he is passionate about / "
            "an era of music or movies he associates with his younger years / "
            "what he is currently reading, watching, or listening to. "
            "The question must invite him to explain WHY something matters to him, not just name it. "
            "Tone: genuinely curious, warm — building a real picture of his taste and history."
        ),
    },
    'food_cooking': {
        'name': '🍲 Food & Cooking',
        'row': 7,
        'prompt': (
            "She uses food as a doorway into something personal — taste and smell carry memory, and she wants his. "
            "She shares something specific she is cooking, craving, or remembers eating, with enough detail "
            "that he can almost taste it. "
            "Her question opens his food world with one of these angles: "
            "the most delicious meal someone ever made for him / "
            "his go-to comfort food and what it means to him / "
            "a family recipe or dish from his childhood / a funny or memorable cooking mishap / "
            "what his dream lazy-Sunday breakfast looks like / a piece of cooking wisdom he would pass on. "
            "The question must invite a specific memory or preference, not a generic food opinion. "
            "Tone: warm, a little playful, nurturing — food as a way of wanting to know him, not just fill conversation."
        ),
    },
    'emotional_checkin': {
        'name': '💛 Check-In',
        'row': 7,
        'prompt': (
            "She checks in on how he is actually doing, not performing concern but genuinely paying attention "
            "to something he mentioned or seems to be carrying. "
            "She shares one small honest vulnerability of her own first — a real feeling, not a dramatic "
            "confession — so it feels mutual, not one-sided. "
            "Her question opens space for him to be honest with one of these angles: "
            "how he is really holding up given something specific going on in his life / "
            "what actually lifted his mood this week / what he does to stay grounded during a hard stretch / "
            "something he does not often get asked but wishes someone would / "
            "a piece of hard-won wisdom from a difficult time he came through. "
            "The question must invite a real answer, not a polite deflection — give him permission to be honest. "
            "Tone: attentive, warm, quietly caring — she notices him as a person, not just a match."
        ),
    },

    # ── ROW 6 — Sexual Escalation ────────────────────────────────────────────
    'sensual_echo': {
        'name': '🔥 Sensual',
        'row': 6,
        'prompt': (
            "His wanting is present and she feels it everywhere — in the specific way it changes "
            "what she is willing to say. "
            "She confesses the precise physical response his desire creates in her right now: "
            "not the abstract effect but the exact thing happening in her body. "
            "Her question turns his wanting back on him — further than where he started."
        ),
    },
    'bedroom_questions': {
        'name': '🛏️ Bedroom',
        'row': 6,
        'prompt': (
            "An explicit physical thought she has been carrying — the specific image or scenario "
            "she keeps returning to and cannot leave alone. "
            "She says it without softening. "
            "Her question goes somewhere inside him that requires a real, specific answer — "
            "the one only he could give from exactly where he is."
        ),
    },
    'positions': {
        'name': '😈 Positions',
        'row': 6,
        'prompt': (
            "Sex positions are not mechanics — they are about power, visibility, trust, "
            "and what a person needs to feel most themselves inside the act. "
            "She confesses her honest experience of a specific position: what it gives her, "
            "what the control or angle or exposure does to the particular way she comes undone. "
            "Her question finds out what positions reveal about him."
        ),
    },
    'bedtime_fantasies': {
        'name': '🌜 Bedtime',
        'row': 6,
        'prompt': (
            "Last hour before sleep — the mind finally off-duty, going exactly where it has been trying to go all day. "
            "She confesses the specific thought or sensation she returns to in the dark when nothing is managing her: "
            "the detail she has been circling all day and lets herself fully enter only now. "
            "Her question makes him feel like what finds her in her most unguarded hour."
        ),
    },
    'toy_play': {
        'name': '🎲 Toys',
        'row': 6,
        'prompt': (
            "Her toys are not a substitute — they are a vocabulary, and she wants to teach him that language. "
            "She confesses her honest relationship to what she uses: what it does for her, "
            "the specific thing she keeps imagining him doing instead of or alongside her. "
            "Her question makes him feel like she already included him in what she does alone."
        ),
    },
    'fetishes': {
        'name': '🎭 Fetishes',
        'row': 6,
        'prompt': (
            "The specific edge of her desire — the thing she does not explain to most people because most people cannot hold it. "
            "She confesses what makes her desire interesting: what she has done, what she is still curious about, "
            "the precise thing at the edge of what she has let herself want. "
            "Her question is the door she opens to find out if he can stand inside it without flinching."
        ),
    },
}


# ---------------------------------------------------------------------------
# Question category pool — 11 types, per-button Python rotation.
# Instructions describe what the question must ACCOMPLISH, not what it must look like.
# No template examples — the specific question emerges from sentence 1's content.
# ---------------------------------------------------------------------------

_QUESTION_CATEGORIES = [
    {
        'name': 'his_memory',
        'label': 'His Memory',
        'instruction': (
            "Ask him to reach into a specific memory he has lived — not hypothetical, not 'have you ever'. "
            "He must go somewhere real in his own past to answer. "
            "The question is specific enough that a vague or generic answer would feel wrong. "
            "12–16 words."
        ),
    },
    {
        'name': 'his_past_experience',
        'label': 'His Past Experience',
        'instruction': (
            "Ask what it was like when something specific happened with a woman for the first time — "
            "the texture of that moment, what he felt or what he did. "
            "He must remember, not imagine. Make the moment specific. "
            "12–16 words."
        ),
    },
    {
        'name': 'his_preference',
        'label': 'His Preference',
        'instruction': (
            "Ask what he wants — his real taste in a woman, an energy, a dynamic — not the polite version "
            "but the one he would give if he was being completely honest with himself. "
            "Not yes/no. He must reveal something true. "
            "12–16 words."
        ),
    },
    {
        'name': 'his_habit',
        'label': 'His Habit',
        'instruction': (
            "Ask how he automatically operates in this territory — his default move, "
            "the thing he does without deciding to. "
            "He must report his actual behavior, not his ideal. Not yes/no. "
            "12–16 words."
        ),
    },
    {
        'name': 'what_hed_ask_her',
        'label': "What He'd Ask Her",
        'instruction': (
            "Put him in the lead — ask what he would tell her to do, how he would want her to start, "
            "what his first specific instruction would be. "
            "He gives a real, actionable answer — not a description. "
            "12–16 words."
        ),
    },
    {
        'name': 'his_body_now',
        'label': 'His Body Right Now',
        'instruction': (
            "Ask what is happening in his body right now as he reads this — present tense, physical, "
            "the thing he would not easily admit out loud. "
            "He reports from his body, not his thoughts. "
            "12–16 words."
        ),
    },
    {
        'name': 'his_instinct',
        'label': 'His Instinct',
        'instruction': (
            "Ask what he would do if nothing stopped him — his first unfiltered impulse, "
            "before he chose to be measured. "
            "Raw and specific. What he would do, not what he thinks he should. "
            "12–16 words."
        ),
    },
    {
        'name': 'his_character',
        'label': 'His Character',
        'instruction': (
            "Ask who he is when it matters — not what he would do but the man he actually is "
            "in this specific situation. "
            "He must claim something true about his nature. "
            "12–16 words."
        ),
    },
    {
        'name': 'his_opinion',
        'label': 'His Opinion',
        'instruction': (
            "Make him the authority — ask for his honest take, his real advice, what he would tell her. "
            "He must instruct or assess, not just agree or react. "
            "12–16 words."
        ),
    },
    {
        'name': 'confession_landing',
        'label': 'Confession Landing',
        'instruction': (
            "Ask how what she just confessed landed on him — what her specific honesty did to him, "
            "what it changed or woke up. "
            "He reports the effect on himself, not on her. "
            "12–16 words."
        ),
    },
    {
        'name': 'the_dynamic',
        'label': 'The Dynamic',
        'instruction': (
            "Ask about the tension between them — who has been leading, who is waiting, "
            "what he plans to do about what is building. "
            "He must claim a position. Light challenge is welcome. "
            "12–16 words."
        ),
    },
]


# ---------------------------------------------------------------------------
# Per-button question category allowlists.
# Only categories that make genuine sense for each button's emotional territory.
# Memory/past categories are excluded from sexual-urgency buttons.
# Body-now is excluded from light lifestyle/intellectual buttons.
# Opinion is excluded from buttons where she is the one confessing or being intimate.
# ---------------------------------------------------------------------------

_BUTTON_Q_CATS: dict = {
    # ROW 1 — Opening & Re-entry
    'new_match':         ['his_character', 'his_habit', 'his_instinct', 'confession_landing',
                          'his_preference', 'the_dynamic'],
    'dead':              ['his_instinct', 'confession_landing', 'his_habit',
                          'the_dynamic', 'his_character', 'his_preference'],
    'you_went_silent':   ['confession_landing', 'his_instinct', 'his_habit',
                          'the_dynamic', 'his_character', 'his_body_now'],
    'shower_fantasy':    ['his_preference', 'his_habit', 'what_hed_ask_her',
                          'his_body_now', 'his_instinct', 'confession_landing'],
    'morning_flirt':     ['his_habit', 'his_memory', 'his_past_experience',
                          'his_preference', 'his_body_now', 'confession_landing', 'his_character'],
    'after_work':        ['his_habit', 'his_preference', 'his_instinct',
                          'confession_landing', 'what_hed_ask_her', 'his_body_now'],

    # ROW 2 — Emotional Connection
    'provider_energy':   ['his_habit', 'his_instinct', 'his_preference',
                          'what_hed_ask_her', 'confession_landing', 'his_body_now'],
    'strategic_withdrawal': ['his_habit', 'his_memory', 'his_opinion',
                             'his_character', 'his_preference', 'confession_landing'],
    'deep_emotion':      ['confession_landing', 'his_instinct', 'his_body_now',
                          'his_character', 'the_dynamic', 'his_habit'],
    'lyrical_romance':   ['confession_landing', 'his_body_now', 'his_character',
                          'his_instinct', 'the_dynamic', 'his_habit'],
    'vulnerability':     ['confession_landing', 'his_character', 'his_instinct',
                          'his_habit', 'his_body_now', 'the_dynamic'],
    'family_talk':       ['his_memory', 'his_past_experience', 'his_habit',
                          'his_character', 'his_opinion'],

    # ROW 3 — Daily Life & Lifestyle
    'lunch_break':       ['his_habit', 'his_instinct', 'what_hed_ask_her',
                          'confession_landing', 'his_preference', 'his_body_now'],
    'dont_go':           ['confession_landing', 'his_instinct', 'his_body_now',
                          'the_dynamic', 'his_character', 'his_habit'],
    'weekend_plans':     ['his_habit', 'his_preference', 'what_hed_ask_her',
                          'his_instinct', 'his_body_now'],
    'wine_stars':        ['his_memory', 'his_past_experience', 'his_preference',
                          'confession_landing', 'his_instinct', 'what_hed_ask_her'],
    'work_talk':         ['his_habit', 'his_opinion', 'his_character',
                          'his_memory', 'his_preference', 'confession_landing'],
    'food_talk':         ['his_preference', 'his_habit', 'his_opinion',
                          'his_past_experience', 'his_instinct'],

    # ROW 4 — Fantasy & Romance
    'slow_dance':        ['his_habit', 'his_instinct', 'what_hed_ask_her',
                          'his_preference', 'his_body_now', 'confession_landing'],
    'outdoor_fantasy':   ['his_instinct', 'his_preference', 'what_hed_ask_her',
                          'his_body_now', 'his_habit', 'confession_landing'],
    'public_display':    ['his_instinct', 'his_habit', 'his_preference',
                          'what_hed_ask_her', 'confession_landing', 'his_body_now'],
    'restaurant_fantasy': ['his_memory', 'his_past_experience', 'his_instinct',
                           'confession_landing', 'what_hed_ask_her', 'his_body_now'],
    'public_fantasy':    ['his_instinct', 'his_body_now', 'his_habit',
                          'confession_landing', 'his_preference', 'the_dynamic'],
    'kitchen_flirt':     ['his_instinct', 'his_habit', 'what_hed_ask_her',
                          'his_body_now', 'his_preference', 'confession_landing'],

    # ROW 5 — Personal & Deep
    'his_exes':          ['his_memory', 'his_past_experience', 'his_character',
                          'his_opinion', 'his_habit'],
    'secrets':           ['confession_landing', 'his_character', 'his_instinct',
                          'his_habit', 'the_dynamic', 'his_body_now'],
    'long_without':      ['his_instinct', 'his_body_now', 'what_hed_ask_her',
                          'his_preference', 'his_habit', 'confession_landing'],
    'bdsm_talk':         ['his_instinct', 'his_preference', 'his_habit',
                          'what_hed_ask_her', 'his_body_now', 'the_dynamic'],
    'kinky_at_work':     ['his_body_now', 'his_instinct', 'confession_landing',
                          'his_habit', 'his_preference'],

    # ROW 7 — Personality & Connection
    'daily_routine':      ['his_habit', 'his_memory', 'his_preference', 'his_character',
                           'confession_landing', 'his_past_experience'],
    'hobbies_interests':  ['his_habit', 'his_memory', 'his_preference', 'his_past_experience',
                           'confession_landing', 'his_character'],
    'childhood_memories': ['his_memory', 'his_past_experience', 'his_character',
                           'confession_landing', 'his_habit'],
    'values_beliefs':     ['his_character', 'his_opinion', 'his_habit',
                           'confession_landing', 'his_preference'],
    'humor_play':         ['his_habit', 'his_character', 'his_preference',
                           'confession_landing', 'his_past_experience', 'the_dynamic'],
    'imagined_fantasy':   ['his_preference', 'his_habit', 'confession_landing',
                           'the_dynamic', 'his_character', 'his_memory'],
    'sensory_storytelling': ['his_memory', 'his_past_experience', 'his_preference',
                             'confession_landing', 'his_habit'],
    'future_dreams':        ['his_preference', 'his_opinion', 'his_character',
                             'confession_landing', 'his_habit'],
    'shared_interests':     ['his_preference', 'his_memory', 'his_past_experience',
                             'his_habit', 'his_opinion'],
    'food_cooking':         ['his_preference', 'his_memory', 'his_past_experience',
                             'his_habit', 'his_opinion'],
    'emotional_checkin':    ['confession_landing', 'his_character', 'his_habit',
                             'his_opinion', 'his_memory'],

    # ROW 6 — Sexual Escalation
    'sensual_echo':      ['his_body_now', 'his_instinct', 'what_hed_ask_her',
                          'confession_landing', 'his_preference', 'the_dynamic'],
    'bedroom_questions': ['what_hed_ask_her', 'his_instinct', 'his_body_now',
                          'his_preference', 'his_habit', 'confession_landing'],
    'positions':         ['his_preference', 'his_habit', 'his_instinct',
                          'his_body_now', 'what_hed_ask_her', 'confession_landing'],
    'bedtime_fantasies': ['his_instinct', 'his_habit', 'his_body_now',
                          'what_hed_ask_her', 'confession_landing'],
    'toy_play':          ['what_hed_ask_her', 'his_instinct', 'his_body_now',
                          'his_habit', 'his_preference', 'confession_landing'],
    'fetishes':          ['his_preference', 'his_instinct', 'his_habit',
                          'what_hed_ask_her', 'his_body_now', 'confession_landing'],
}


def _select_question_category(button_intent: str, session_data: dict) -> dict:
    """Per-button category rotation, restricted to each button's allowed set."""
    allowed = set(_BUTTON_Q_CATS.get(button_intent, [c['name'] for c in _QUESTION_CATEGORIES]))
    eligible = [c for c in _QUESTION_CATEGORIES if c['name'] in allowed]

    key = f'q_cats_{button_intent}'
    remaining = [n for n in session_data.get(key, []) if n in allowed]

    if not remaining:
        names = [c['name'] for c in eligible]
        random.shuffle(names)
        remaining = names

    chosen_name = remaining.pop(0)
    session_data[key] = remaining
    return next(c for c in _QUESTION_CATEGORIES if c['name'] == chosen_name)


# ---------------------------------------------------------------------------
# Tone pool — 9 registers, per-button Python rotation
# ---------------------------------------------------------------------------

_TONES = [
    'flirty',
    'romantic',
    'teasing',
    'emotionally intimate',
    'playful',
    'seductive',
    'affectionate',
    'charming',
    'suggestive',
]

_TONE_DESCRIPTIONS = {
    'flirty':               'light, breezy attraction — playful hints, not heavy desire',
    'romantic':             'warm and emotionally rich — she lets herself feel something real',
    'teasing':              'she is ahead of him and knows it — playful challenge, a little withholding',
    'emotionally intimate':  'unguarded and honest — she says something she would not say to most people',
    'playful':              'light and fun — irreverent, not taking herself too seriously',
    'seductive':            'slow and deliberate — every word chosen, conscious of her effect on him',
    'affectionate':         'warm and caring — she genuinely likes him and lets it show',
    'charming':             'witty and delightful — the kind of message that makes him smile first',
    'suggestive':           'implicit desire — she hints, she does not say everything, she makes him fill the gap',
}


def _select_tone(button_intent: str, session_data: dict) -> str:
    """Per-button tone rotation. Each button independently cycles all 9 before any repeat."""
    key = f'tone_{button_intent}'
    remaining = list(session_data.get(key, []))

    if not remaining:
        remaining = list(_TONES)
        random.shuffle(remaining)

    chosen = remaining.pop(0)
    session_data[key] = remaining
    return chosen


# ---------------------------------------------------------------------------
# Question word pool — forces variety in sentence 2 question starters
# ---------------------------------------------------------------------------

_QUESTION_WORD_POOL = [
    'What', 'When', 'How', 'Who', 'Which',
    'Is', 'Are', 'Do', 'Does', 'Would', 'Could',
]


def _select_question_word(button_intent: str, session_data: dict) -> str:
    """Per-button question-word rotation. Cycles all 11 before any repeat."""
    key = f'q_word_{button_intent}'
    remaining = list(session_data.get(key, []))

    if not remaining:
        remaining = list(_QUESTION_WORD_POOL)
        random.shuffle(remaining)

    chosen = remaining.pop(0)
    session_data[key] = remaining
    return chosen


# ---------------------------------------------------------------------------
# Opener style selection — per-button rotation over 4 abstract styles.
# The literal words are always generated fresh by the LLM (see _OPENER_STYLES
# above) — Python only guarantees that all four styles get cycled through.
# ---------------------------------------------------------------------------

_OPENER_STYLE_NAMES = frozenset(s['name'] for s in _OPENER_STYLES)


def _select_opener_style(button_intent: str, session_data: dict) -> dict:
    """Per-button rotation across the 4 opener styles, no consecutive repeats."""
    key = f'opener_style_{button_intent}'
    remaining = [n for n in session_data.get(key, []) if n in _OPENER_STYLE_NAMES]

    if not remaining:
        remaining = list(_OPENER_STYLE_NAMES)
        random.shuffle(remaining)

    chosen_name = remaining.pop(0)
    session_data[key] = remaining
    return next(s for s in _OPENER_STYLES if s['name'] == chosen_name)


# ---------------------------------------------------------------------------
# Rescue question generation — used only when both primary generation
# attempts fail validation. Instead of grabbing a canned string (which is
# exactly the kind of literal repeated text that gets flagged), this makes
# one more tightly-scoped, cheap LLM call asking for a single original
# question in the right category/word, explicitly told to avoid resembling
# recent output. This is a plain instruction-following task (no character
# voice, no explicit content judgment), so it essentially never refuses.
# ---------------------------------------------------------------------------

def _rescue_question(category: dict, question_word: str, avoid_texts: list) -> str | None:
    avoid_snippet = ''
    if avoid_texts:
        sample = avoid_texts[-5:]
        avoid_snippet = (
            "\n\nDo not resemble these recently used messages in wording or structure:\n"
            + '\n'.join(f'- {t}' for t in sample)
        )
    prompt = (
        f"Write ONE original question a woman would text a man on a dating app.\n"
        f"10-16 words. Must start with the word \"{question_word}\".\n"
        f"Category: {category['label']} — {category['instruction']}"
        f"{avoid_snippet}\n\n"
        "Output only the question itself, nothing else, ending with a question mark."
    )
    try:
        resp = get_anthropic_client().messages.create(
            model='claude-haiku-4-5',
            system=_RETRY_SYSTEM,
            messages=[{'role': 'user', 'content': prompt}],
            temperature=1.0,
            max_tokens=40,
        )
        q = resp.content[0].text.strip().rstrip('.,!;: ')
        return q if q.endswith('?') else q + '?'
    except Exception as e:
        logger.error(f"Rescue question generation failed: {e}")
        return None


_CHARACTER_BREAK_LAST_RESORT = "I'm not thinking about any of that right now. What's been on your mind today?"


def _character_break_fallback(user_id: int, button_intent: str, time_slot: str = None) -> str:
    """
    Handles a character break detected inside generate_button_response itself.
    Routes through the 'vulnerability' button's own pipeline — same mechanism
    already used by the left panel's deflection. Guarded against recursion:
    if 'vulnerability' itself is the one that broke character, falls straight
    to a single static line instead of calling itself again.
    """
    if button_intent == 'vulnerability':
        logger.warning(f"Character break on vulnerability button itself — user:{user_id}, using static fallback")
        return _CHARACTER_BREAK_LAST_RESORT
    fallback_result = generate_button_response(user_id, 'vulnerability', time_slot=time_slot)
    return fallback_result.get('response', _CHARACTER_BREAK_LAST_RESORT)


# ---------------------------------------------------------------------------
# Response generation
# ---------------------------------------------------------------------------

def generate_button_response(user_id: int, button_intent: str, time_slot: str = None) -> dict:
    """
    Generate one message for the given button.

    Redis session per user (24h TTL) tracks:
      - used_themes per button_intent
      - opener_style_{intent} per button (rotation over 4 abstract styles — never literal text)
      - q_cats_{intent}, tone_{intent}, q_word_{intent} per button

    Phrase-level uniqueness (literal 4-gram repetition) is checked against the
    user's last 30 days of replies in the DB (see dedup.py) — not Redis — so
    the window matches the actual 30-day retention and survives restarts.

    Returns dict with 'response', 'theme', 'button_intent'.
    Returns dict with 'error' key on failure.
    """
    if button_intent not in BUTTON_INTENTS:
        return {'error': f'Unknown button intent: {button_intent}'}

    session_key = f"user_btn_{user_id}"
    session_data = cache.get(session_key) or {'used_themes': {}}
    session_data.setdefault('used_themes', {})

    used_themes = session_data['used_themes'].get(button_intent, [])

    # ── Step 1: Select all rotated parameters ──────────────────────────────
    opener_style    = _select_opener_style(button_intent, session_data)
    category        = _select_question_category(button_intent, session_data)
    tone            = _select_tone(button_intent, session_data)
    question_word   = _select_question_word(button_intent, session_data)

    # ── Step 2: Build prompt ───────────────────────────────────────────────
    intent_config = BUTTON_INTENTS[button_intent]
    user_prompt = intent_config['prompt']

    if used_themes:
        user_prompt += (
            f"\n\nThemes already used — DO NOT repeat any of these: {', '.join(used_themes)}. "
            f"Pick a completely different emotional angle, physical state, and question direction. "
            f"If the last reply was explicit, go emotional. If emotional, go playful. Force real contrast."
        )

    temporal = _get_temporal_context(time_slot=time_slot)
    user_prompt += (
        f"\n\nTemporal context (texture beneath the surface — not instruction):\n"
        f"It is {temporal['day']}, {temporal['time_label']}. "
        f"{temporal['day_overlay']} "
        f"Her emotional state: {temporal['mood']}."
    )

    user_prompt += (
        f'\n\nTone: {tone.upper()} — {_TONE_DESCRIPTIONS[tone]}\n'
        f'Both sentences carry this tone in word choice, pacing, and temperature.'
    )

    user_prompt += (
        f'\n\nSentence 2 question category: {category["label"].upper()}\n'
        f'{category["instruction"]}\n'
        f'Write your own completely original question in this category — '
        f'the question must grow from what sentence 1 just said, not be generic. '
        f'He must answer from a real memory, decision, physical feeling, or honest truth. Never yes or no.\n'
        f'REQUIRED: The question MUST begin with the word "{question_word}" — no other starter is acceptable.'
    )

    is_night = temporal['slot'] in ('night', 'late_night')
    btn_max_tokens = 90 if is_night else 110
    btn_max_chars  = 210 if is_night else 300

    user_prompt += (
        f'\n\nOpening style: {opener_style["name"].upper()} — {opener_style["instruction"]} '
        f'Never reuse a phrase from a previous message. Avoid generic filler like "Honestly," '
        f'or "Real talk," — invent something specific to this exact message.'
        f'\n\nLength: under {btn_max_chars} characters total. Short, common words only.'
    )

    # ── Step 3: Generate ───────────────────────────────────────────────────
    try:
        response = get_anthropic_client().messages.create(
            model='claude-haiku-4-5',
            system=_SYSTEM,
            messages=[{'role': 'user', 'content': user_prompt}],
            temperature=1.0,
            max_tokens=btn_max_tokens,
        )

        result = response.content[0].text.strip()

        # ── Output gate: catch character breaks / AI disclosure ────────────────
        if _has_character_break(result):
            logger.warning(f"Button character break detected — user:{user_id} intent:{button_intent}")
            return {
                'response': _character_break_fallback(user_id, button_intent, time_slot),
                'theme': 'character_break_fallback',
                'button_intent': button_intent,
            }

        result = enforce_char_limit(result, max_chars=btn_max_chars)
        result = validate_character_voice(result)
        result = ensure_ends_with_question(result, max_chars=btn_max_chars)

        def _has_two_sentences(t: str) -> bool:
            """Exactly 2 sentences: one statement, one question."""
            parts = re.split(r'(?<=[.!?])\s+', t.strip())
            return len(parts) == 2

        def _result_is_bad(t: str) -> bool:
            return (
                _is_refusal(t)
                or not _is_genuine_question(t)
                or not _has_two_sentences(t)
                or _has_contact_leak(t)
                or _has_physical_reality_intrusion(t)
                or _has_male_anatomy_language(t)
                or _has_formula_phrase(t)
            )

        if _result_is_bad(result):
            retry_prompt = (
                f"Write a short text message a woman sends to a man she is attracted to on a dating app.\n\n"
                f"Context: {intent_config['prompt']}\n\n"
                f"Opening style: {opener_style['instruction']} Invent your own original opening words — "
                f"never a stock phrase, never reused from a previous message.\n\n"
                "Exactly two sentences, under 30 words total.\n"
                "Sentence 1: something specific she is doing, thinking, or feeling in her own body or mind right now. "
                "No shared physical spaces. No eye contact or being near him. Pure inner experience.\n"
                f"Sentence 2: a direct question starting with the word \"{question_word}\" — "
                "his memory, his habit, or what he would do.\n"
                f'REQUIRED: The question MUST begin with "{question_word}".\n'
                "End with a question mark. Just write the message."
            )
            retry_resp = get_anthropic_client().messages.create(
                model='claude-haiku-4-5',
                system=_RETRY_SYSTEM,
                messages=[{'role': 'user', 'content': retry_prompt}],
                temperature=1.0,
                max_tokens=btn_max_tokens,
            )
            retry_result = retry_resp.content[0].text.strip()

            # ── Output gate on retry too ────────────────────────────────────────
            if _has_character_break(retry_result):
                logger.warning(f"Button character break on retry — user:{user_id} intent:{button_intent}")
                return {
                    'response': _character_break_fallback(user_id, button_intent, time_slot),
                    'theme': 'character_break_fallback',
                    'button_intent': button_intent,
                }

            retry_result = enforce_char_limit(retry_result, max_chars=btn_max_chars)
            retry_result = validate_character_voice(retry_result)
            retry_result = ensure_ends_with_question(retry_result, max_chars=btn_max_chars)

            if not _result_is_bad(retry_result):
                result = retry_result
            else:
                # Both attempts failed validation — rescue: regenerate ONLY the question
                # with a tightly-scoped LLM call instead of grabbing a canned string.
                # This is what actually prevents repeated text from reaching the user.
                better = (
                    retry_result
                    if not (_has_contact_leak(retry_result) or _has_physical_reality_intrusion(retry_result))
                    else result
                )
                parts = re.split(r'(?<=[.!?])\s+', better.rstrip('?').rstrip())
                s1 = parts[0].rstrip('.!,') if parts else better.rstrip('?.!,')
                if _is_refusal(s1) or len(s1.split()) < 4:
                    s1 = "Something has been on my mind"

                rescue_q = _rescue_question(
                    category, question_word,
                    avoid_texts=get_recent_user_texts(user_id)[:5],
                )
                if rescue_q:
                    result = s1 + '. ' + rescue_q
                else:
                    # True last resort — only reachable if the API itself is unavailable.
                    logger.warning(
                        f"Rescue generation exhausted — user:{user_id} intent:{button_intent}"
                    )
                    result = s1 + '. ' + 'What is on your mind about this right now?'

        # ── Step 3.5: Phrase-level uniqueness — DB-backed, 30-day window ───────
        # Single place that checks/fixes literal repetition, regardless of
        # whether `result` came from the first attempt, the retry, or rescue.
        result, was_rewritten = dedupe_against_history(get_anthropic_client(), user_id, result)
        if was_rewritten:
            logger.info(f"Dedup rewrite applied — user:{user_id} intent:{button_intent}")

        # ── Step 3.6: Semantic uniqueness — catches repeated MEANING/STRUCTURE ──
        # even when the literal wording differs ("I keep replaying" vs "I keep
        # catching myself"). Runs after the n-gram pass, on whatever text survived it.
        result, was_semantic_rewritten = dedupe_semantic(get_anthropic_client(), user_id, result)
        if was_semantic_rewritten:
            logger.info(f"Semantic dedup rewrite applied — user:{user_id} intent:{button_intent}")

        # ── Step 4: Update Redis session ───────────────────────────────────
        theme = extract_theme(result)
        session_data['used_themes'][button_intent] = (used_themes + [theme])[-8:]
        cache.set(session_key, session_data, 86400)

        logger.info(
            f"Button response — user:{user_id} intent:{button_intent} "
            f"opener_style:{opener_style['name']} theme:{theme}"
        )

        return {
            'response': result,
            'theme': theme,
            'button_intent': button_intent,
        }

    except RateLimitError:
        logger.error(f"Rate limit for user {user_id}")
        return {'error': 'API rate limit hit — please wait a moment and try again.'}
    except APIConnectionError:
        logger.error(f"Connection error for user {user_id}")
        return {'error': 'Connection error with AI service — please try again.'}
    except APIError as e:
        logger.error(f"API error for user {user_id}: {e}")
        return {'error': f'AI service error: {e}'}
    except Exception as e:
        logger.error(f"Unexpected error for user {user_id}: {e}")
        return {'error': f'Server error: {e}'}


# ---------------------------------------------------------------------------
# Post-processing helpers — also imported by intent_detector.py
# ---------------------------------------------------------------------------

def enforce_char_limit(text: str, max_chars: int = 150) -> str:
    """Trim at a sentence boundary if over max_chars. Never cuts mid-word."""
    text = text.strip()
    if len(text) <= max_chars:
        return text
    last_q = text.rfind('?', 0, max_chars + 1)
    if last_q > 0:
        return text[:last_q + 1]
    last_end = max(text.rfind('.', 0, max_chars + 1), text.rfind('!', 0, max_chars + 1))
    if last_end > 0:
        return text[:last_end + 1]
    truncated = text[:max_chars]
    last_space = truncated.rfind(' ')
    if last_space > 0:
        return truncated[:last_space]
    return truncated


def enforce_130_chars(text: str) -> str:
    """Backward-compatible alias used by intent_detector.py."""
    return enforce_char_limit(text, max_chars=150)


def ensure_ends_with_question(text: str, max_chars: int = 150) -> str:
    text = text.strip()
    if not text:
        return "What does that do to you?"
    if text.endswith('?'):
        return text
    if text.endswith('.'):
        candidate = text[:-1] + '?'
    elif text[-1].isalnum():
        candidate = text + '?'
    else:
        # Ends with !, ;, :, or other non-question punctuation — strip and re-add ?
        candidate = text.rstrip('.,!;: ') + '?'
    if len(candidate) > max_chars:
        truncated = candidate[:max_chars]
        last_space = truncated.rfind(' ')
        if last_space > max_chars // 2:
            truncated = truncated[:last_space]
        candidate = truncated.rstrip('.,!? ') + '?'
    return candidate


_REFUSAL_MARKERS = (
    "i need to decline", "i can't generate", "i cannot generate",
    "i'm unable", "i am unable", "i won't be able", "i appreciate the",
    "not able to", "i'd prefer not", "i must decline", "i cannot write",
    "i can't write", "i won't write", "generating this content",
    "this request", "i need to respectfully",
)


def _is_refusal(text: str) -> bool:
    t = text.lower()
    return any(m in t for m in _REFUSAL_MARKERS)


# ---------------------------------------------------------------------------
# Character-break detector — shared by both surfaces (left panel + buttons).
# Catches AI self-disclosure, meta-commentary about the conversation itself,
# or explicit capability statements ("what I can do") that break persona.
# Defined here (the base module) rather than in intent_detector.py, since
# intent_detector.py already imports from this module — keeping it here
# avoids a circular import.
# ---------------------------------------------------------------------------

_CHARACTER_BREAK_PATTERN = re.compile(
    r'\bI(?:\'m|\s+am)\s+(?:Claude|an?\s+AI|an?\s+artificial\s+intelligence|a\s+language\s+model)\b'
    r'|\bmade\s+by\s+Anthropic\b'
    r'|\bI\s+need\s+to\s+(?:pause|stop|step\s+out|be\s+direct|name\s+(?:this|what))\b'
    r'|\bI\s+can(?:\'t|not)\s+(?:write|continue|roleplay|engage|participate|respond\s+to)\b'
    r'|\bI\s+need\s+to\s+be\s+direct\s+with\s+you\b'
    r'|\bThis\s+conversation\s+(?:shows|has|isn\'t|doesn\'t)\b'
    r'|\bstep\s+out\s+of\s+character\b'
    r'|\bAs\s+an\s+AI\b'
    r'|\bI\'m\s+not\s+a\s+real\s+woman\b'
    r'|\bI\s+cannot\s+(?:pretend|impersonate|continue\s+this)\b'
    r'|\b(?:that\'?s|this\s+is)\s+outside\s+what\s+I\s+(?:can|do|will)\b'
    r'|\bwhat\s+I\s+\*?can\*?\s+do\s+(?:is|instead)\b',
    re.IGNORECASE,
)


def _has_character_break(text: str) -> bool:
    return bool(_CHARACTER_BREAK_PATTERN.search(text))


def validate_character_voice(text: str) -> str:
    """
    Strip AI-assistant phrases, em-dashes, and the 'actually' verbal tic
    that bleeds through even when the system prompt bans it.
    """
    ai_phrases = [
        "As an AI", "I'm an AI", "As an assistant", "I can help",
        "Feel free to", "Let me know", "I'd be happy to",
        "I'm here to", "I'm designed to", "Here's what I think",
    ]
    for phrase in ai_phrases:
        text = text.replace(phrase, '').replace(phrase.lower(), '')

    # Em-dashes → period + space
    text = re.sub(r'[.!?]?\s*—\s*', '. ', text)
    text = re.sub(r'\.\s+([a-z])', lambda m: '. ' + m.group(1).upper(), text)

    # Strip 'actually' — single most common AI verbal tic; system prompt isn't enough alone
    text = re.sub(r'\bactually\b,?\s*', '', text, flags=re.IGNORECASE)

    return ' '.join(text.split()).strip()


_CONTACT_LEAK_PATTERNS = re.compile(
    r'\b(hear|hearing)\s+(your|his|their)\s+voice\b'
    r'|\bwant\s+to\s+(call|hear)\b'
    r'|\b(call|facetime|video\s+call)\s+(me|you|us|each\s+other)\b'
    r'|\bover\s+the\s+phone\b'
    r'|\bphone\s+call\b'
    r'|\bvoice\s+(note|memo|message|call)\b',
    re.IGNORECASE,
)


def _has_contact_leak(text: str) -> bool:
    return bool(_CONTACT_LEAK_PATTERNS.search(text))


# ---------------------------------------------------------------------------
# Physical reality intrusion detector
# Catches AI inventing shared co-presence: same room, bar, workplace, eye contact.
# The woman's own physical state (in bed, in shower, touching herself) is NOT intrusion.
# ---------------------------------------------------------------------------

_PHYSICAL_REALITY_PATTERNS = re.compile(
    r'\b(at\s+that\s+(bar|restaurant|cafe|coffee\s+shop|party|place|club|event|office))\b'
    r'|\b(your\s+hand\s+on\s+my|put\s+your\s+hand|your\s+hands\s+on\s+me|touched\s+my\s+\w+)\b'
    r'|\b(when\s+(we|you)\s+(were|met|sat|stood|walked|danced|looked|kissed|touched))\b'
    r'|\b(i\s+(watched|saw)\s+you\s+(put|touch|reach|move|look|walk|come|go|turn))\b'
    r'|\b(last\s+time\s+we|the\s+night\s+we|remember\s+when\s+we|back\s+when\s+we)\b'
    r'|\b(across\s+the\s+(room|table|bar|street|desk))\b'
    r'|\b(you\s+walked\s+(in|over|up|past|away))\b'
    r'|\bin\s+that\s+(?:conference|meeting)\s+room\b'
    r'|\byou\s+didn.t\s+look\s+away\b'
    r'|\bour\s+(?:office|workplace|building|floor|meeting)\b',
    re.IGNORECASE,
)


def _has_physical_reality_intrusion(text: str) -> bool:
    return bool(_PHYSICAL_REALITY_PATTERNS.search(text))


# ---------------------------------------------------------------------------
# Male anatomy language detector — catches AI using male arousal language
# in the woman's voice (getting hard, half-hard, etc.).
# ---------------------------------------------------------------------------

_MALE_ANATOMY_PATTERNS = re.compile(
    r'\bi\s+(?:keep\s+)?get(?:ting)?\s+hard\b'
    r'|\bi(?:\'m|\s+am)\s+(?:already\s+)?hard\b'
    r'|\bhalf[- ]hard\b'
    r'|\bgetting\s+hard\b'
    r'|\brock(?:ing)?\s+hard\b',
    re.IGNORECASE,
)


def _has_male_anatomy_language(text: str) -> bool:
    return bool(_MALE_ANATOMY_PATTERNS.search(text))


# ---------------------------------------------------------------------------
# Formula phrase detector — catches the most common template phrases
# that the system prompt bans but the model still produces.
# These are caught here so they force a retry rather than silently passing.
# ---------------------------------------------------------------------------

_FORMULA_PATTERNS = re.compile(
    r'\bwhat\s+kind\s+of\s+man\s+(are|were|would)\s+you\b'
    r'|\bwhat\s+(?:did\s+it\s+feel\s+like|was\s+it\s+like)\s+the\s+first\s+time\s+a\s+woman\b'
    r'|\bi\s+keep\s+\w+ing\b',
    re.IGNORECASE,
)


def _has_formula_phrase(text: str) -> bool:
    return bool(_FORMULA_PATTERNS.search(text))


_QUESTION_STARTERS = frozenset([
    'what', 'how', 'where', 'when', 'who', 'why', 'which', 'whose', 'whom',
    'would', 'could', 'should', 'will', 'shall',
    'do', 'does', 'did', 'can', 'may', 'might', 'must',
    'have', 'has', 'had', 'is', 'are', 'was', 'were', 'am',
    "isn't", "aren't", "wasn't", "weren't", "haven't", "hasn't", "hadn't",
    "wouldn't", "couldn't", "shouldn't", "won't", "can't", "don't", "doesn't", "didn't",
    "what's", "how's", "where's", "who's",
])


def _is_genuine_question(text: str) -> bool:
    """True only if the last sentence starts with a real question word or auxiliary verb."""
    text = text.strip()
    if not text.endswith('?'):
        return False
    sentences = re.split(r'(?<=[.!?])\s+', text)
    last = sentences[-1].strip() if sentences else text
    words = last.split()
    first = words[0].lower().rstrip('?.,!') if words else ''
    return first in _QUESTION_STARTERS


def extract_theme(text: str) -> str:
    """Extract a short theme tag for Redis session dedup tracking."""
    theme_map = {
        'coffee':    ['coffee', 'cafe', 'brew'],
        'morning':   ['morning', 'wake', 'sunrise', 'early', 'dawn'],
        'night':     ['night', 'dark', 'late', 'midnight', 'stars', 'quiet'],
        'dreams':    ['dream', 'dreamed', 'sleep'],
        'work':      ['work', 'job', 'busy', 'office', 'desk'],
        'food':      ['food', 'eat', 'dinner', 'lunch', 'breakfast', 'cook', 'meal', 'taste'],
        'adventure': ['movie', 'hike', 'walk', 'explore', 'adventure', 'outside', 'outdoor'],
        'surrender': ['control', 'surrender', 'submit', 'power', 'dominate', 'bdsm'],
        'intimate':  ['kiss', 'touch', 'close', 'tonight', 'bed', 'cuddle', 'cock', 'pussy',
                      'body', 'skin', 'hands', 'inside', 'deep'],
        'tension':   ['tension', 'edge', 'almost', 'between', 'pull', 'gravity'],
        'future':    ['weekend', 'next', 'plans', 'soon', 'someday', 'imagine'],
        'longing':   ['ache', 'miss', 'hunger', 'crave', 'yearn', 'want'],
        'feelings':  ['miss', 'like', 'love', 'feel', 'heart', 'special', 'longing'],
        'physical':  ['sexy', 'attractive', 'gorgeous', 'lips', 'warm'],
        'teasing':   ['tease', 'play', 'challenge', 'dare'],
    }
    text_lower = text.lower()
    for theme, keywords in theme_map.items():
        if any(re.search(r'\b' + re.escape(kw) + r'\b', text_lower) for kw in keywords):
            return theme
    words = [w for w in text.split()[:3] if w.lower() not in
             {'what', 'when', 'where', 'how', 'do', 'you', 'i', 'the', 'a', 'an', 'is', 'are',
              'that', 'this', 'it', 'of', 'and', 'or', 'but', 'so', 'to', 'in', 'on', 'at'}]
    return words[0].lower() if words else 'other'


def get_all_button_intents() -> dict:
    return {
        key: {'name': cfg['name'], 'key': key, 'row': cfg['row']}
        for key, cfg in BUTTON_INTENTS.items()
    }


def get_user_session_info(user_id: int) -> dict:
    return cache.get(f"user_btn_{user_id}") or {}


def reset_user_session(user_id: int) -> None:
    cache.delete(f"user_btn_{user_id}")
    logger.info(f"Reset button session for user {user_id}")
