"""
Django settings for flirty_backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
import environ

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment
env = environ.Env()

# Try to read .env file from multiple possible locations
env_path = os.path.join(BASE_DIR, ".env")
if os.path.exists(env_path):
    environ.Env.read_env(env_path)
else:
    # If .env doesn't exist, that's OK - environment variables can come from docker-compose/container env
    pass

# NOW safe to use env
try:
    SECRET_KEY = env("SECRET_KEY")
except KeyError:
    print("ERROR: SECRET_KEY not found in environment or .env file!")
    print(f"Looking for .env at: {env_path}")
    print(f"File exists: {os.path.exists(env_path)}")
    raise EnvironmentError("SECRET_KEY must be set in environment variables or .env file")

DEBUG = env.bool("DEBUG", default=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'pgvector.django',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flirty_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flirty_backend.wsgi.application'





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB', default='flirty'),
        'USER': env('POSTGRES_USER', default='flirty'),
        'PASSWORD': env('POSTGRES_PASSWORD', default='flirty'),
        'HOST': env('POSTGRES_HOST', default='db'),  
        'PORT': env('POSTGRES_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#password-validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# DEBUG=False stops Django's runserver from serving static files itself —
# WhiteNoise serves them directly from gunicorn instead, so nginx doesn't
# need its own config/volume for Django admin's CSS/JS. Requires running
# `python manage.py collectstatic --noinput` once during deploy.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production sets CORS_ALLOWED_ORIGINS=https://flirtfyai.site,https://www.flirtfyai.site
# in its own .env — these dev defaults stay untouched either way.
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://frontend:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
])

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']

# Production-only hardening — gated on DEBUG so local dev (plain HTTP) is
# never affected. nginx terminates TLS and proxies plain HTTP to gunicorn,
# so Django needs SECURE_PROXY_SSL_HEADER to trust nginx's X-Forwarded-Proto
# header — without it, SECURE_SSL_REDIRECT would redirect-loop forever
# (Django would see every proxied request as HTTP and keep "redirecting" to HTTPS).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Production .env: CSRF_TRUSTED_ORIGINS=https://flirtfyai.site,https://www.flirtfyai.site
    CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Allow framing for development (set to SAMEORIGIN or DENY in production)
X_FRAME_OPTIONS = 'SAMEORIGIN'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # Used by accounts.throttles — applied only to the AI-generation endpoints,
    # not globally, since other endpoints (login, register) don't need this.
    'DEFAULT_THROTTLE_RATES': {
        'generation_burst': '20/min',
        'generation_daily': '300/day',
        'payment_initiate': '5/min',
    },
}


# Redis cache for production
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://redis:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://redis:6379/0")
CELERY_TASK_ALWAYS_EAGER = False
CELERY_RESULT_EXTENDED = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Periodic tasks — requires a `celery beat` process running (see docker-compose.yml)
from celery.schedules import crontab  # noqa: E402
CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-replies': {
        'task': 'accounts.tasks.cleanup_expired_replies',
        'schedule': crontab(hour=3, minute=0),  # daily, low-traffic hour
    },
}

# Django Celery Results
INSTALLED_APPS += ['django_celery_results']

# API Configuration
OPENAI_API_KEY = env("OPENAI_API_KEY", default="")
ANTHROPIC_API_KEY = env("ANTHROPIC_API_KEY", default="")

if not ANTHROPIC_API_KEY:
    print("⚠️ WARNING: ANTHROPIC_API_KEY not set in environment variables")

# M-Pesa Daraja API — see accounts/services/mpesa_service.py for the full
# contract. Blank by default; payments cannot work until real credentials
# from https://developer.safaricom.co.ke are set, and MPESA_CALLBACK_URL is
# a publicly reachable HTTPS URL (Safaricom cannot call localhost).
MPESA_ENV = env("MPESA_ENV", default="sandbox")  # 'sandbox' or 'production'
MPESA_CONSUMER_KEY = env("MPESA_CONSUMER_KEY", default="")
MPESA_CONSUMER_SECRET = env("MPESA_CONSUMER_SECRET", default="")
MPESA_SHORTCODE = env("MPESA_SHORTCODE", default="174379")  # 174379 = Daraja's public sandbox test shortcode
MPESA_PASSKEY = env("MPESA_PASSKEY", default="")
MPESA_CALLBACK_URL = env("MPESA_CALLBACK_URL", default="")

if MPESA_ENV == "production" and not (MPESA_CONSUMER_KEY and MPESA_PASSKEY and MPESA_CALLBACK_URL):
    print("⚠️ WARNING: MPESA_ENV=production but credentials/callback URL are incomplete")

# Subscription pricing — $10 USD, quoted to M-Pesa in KES (M-Pesa only
# transacts in KES). The KES amount and click count are both starting
# assumptions — confirm the real exchange rate and adjust SUBSCRIPTION_CLICKS
# to taste before going live.
SUBSCRIPTION_PRICE_USD = 10
SUBSCRIPTION_PRICE_KES = env.int("SUBSCRIPTION_PRICE_KES", default=1300)
SUBSCRIPTION_CLICKS = env.int("SUBSCRIPTION_CLICKS", default=200)

# Django Channels Configuration (for WebSocket support)
# This connects to your WSL Redis instance
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    }
}

# Logging — without this, logger.info() calls anywhere in the app are
# silently dropped (Python's root logger defaults to WARNING). This makes
# them print to stdout, which gunicorn/docker compose logs picks up.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}