"""
OpenAI Integration Service
Handles all interactions with OpenAI API for natural language responses
"""

import os
import json
import httpx
from openai import OpenAI
from django.core.cache import cache

# Initialize OpenAI client lazily (only when needed to avoid import errors)
# Get your API key from: https://platform.openai.com/api/keys
_client = None

def get_openai_client():
    """Lazy-load and return the OpenAI client with custom httpx client"""
    global _client
    if _client is None:
        api_key = os.getenv('OPENAI_API_KEY')
        if not api_key:
            raise ValueError("OPENAI_API_KEY environment variable not set")
        
        # Create a custom httpx client without problematic parameters
        # This avoids httpx version compatibility issues
        try:
            http_client = httpx.Client()
            _client = OpenAI(api_key=api_key, http_client=http_client)
        except Exception as e:
            # Fallback to default client if custom client fails
            _client = OpenAI(api_key=api_key)
    return _client


class UniqueResponseTracker:
    """
    Tracks responses to ensure they don't repeat or use similar phrases.
    Prevents the AI from giving the same answer twice in two months (60 days).
    """
    
    def __init__(self, user_id, time_period_days=60):
        """
        Initialize tracker for a specific user
        
        Args:
            user_id: Django user ID
            time_period_days: How many days to track responses (default: 60 days / 2 months)
        """
        self.user_id = user_id
        self.cache_key = f"response_history_{user_id}"
        self.time_period = time_period_days * 24 * 60 * 60  # Convert to seconds
    
    def get_response_history(self):
        """Retrieve all responses generated by this user in the tracking period"""
        return cache.get(self.cache_key, [])
    
    def add_response(self, response_text):
        """Add a new response to the tracking history, keeping only the last 45 days"""
        history = self.get_response_history()
        # Each entry: (response_text, timestamp)
        from datetime import datetime, timedelta
        now = datetime.utcnow()
        # If history is just a list of strings, convert to list of tuples
        if history and isinstance(history[0], str):
            history = [(h, now) for h in history]
        # Add new response
        history.append((response_text, now))
        # Prune entries older than 45 days
        cutoff = now - timedelta(days=45)
        history = [(text, ts) for text, ts in history if ts >= cutoff]
        # Save only the text part for compatibility
        cache.set(self.cache_key, [text for text, ts in history], self.time_period)
    
    def get_similar_responses(self, text):
        """
        Find previously generated responses that are similar to the current one
        Uses basic similarity checking on sentence level
        """
        history = self.get_response_history()
        sentences = text.split('.')
        
        similar = []
        for prev_response in history:
            prev_sentences = prev_response.split('.')
            for sentence in sentences:
                for prev_sentence in prev_sentences:
                    if self._is_similar(sentence.strip(), prev_sentence.strip()):
                        similar.append(prev_response)
        
        return similar
    
    @staticmethod
    def _is_similar(text1, text2, threshold=0.7):
        """
        Check if two sentences are similar using word overlap
        Returns True if similarity > threshold
        """
        if not text1 or not text2:
            return False
        
        words1 = set(text1.lower().split())
        words2 = set(text2.lower().split())
        
        if not words1 or not words2:
            return False
        
        intersection = len(words1 & words2)
        union = len(words1 | words2)
        
        similarity = intersection / union if union > 0 else 0
        return similarity > threshold


class OpenAIService:
    """
    Service for handling all OpenAI API calls
    Uses GPT-3.5-turbo for cost-effective, natural responses
    """
    
    # Configuration constants
    MODEL = "gpt-4"
    TEMPERATURE = 0.8  # Higher = more creative (0-1 scale)
    MAX_TOKENS = 300
    
    @staticmethod
    def generate_response(user_id, conversation_text, previous_responses=None):
        """
        Generates a unified response using the shared ResponseValidator.
        Delegates to generate_reply() for consistency across chat and task paths.
        """
        import logging
        from django.contrib.auth.models import User
        from accounts.services.ai_generation import generate_reply
        
        logger = logging.getLogger(__name__)
        try:
            user = User.objects.get(id=user_id)
            logger.info(f"Generating AI reply for user {user_id} via OpenAIService")
            
            # Delegate to unified generator with ResponseValidator
            response_text = generate_reply(conversation_text, user=user, attempt_number=1)
            
            # Check if response is an error
            if response_text.startswith('report!'):
                return {
                    'success': False,
                    'response': response_text,
                    'is_unique': True,
                    'original_response': None
                }
            
            logger.info(f"Final AI reply sent to user {user_id}")
            return {
                'success': True,
                'response': response_text,
                'is_unique': True,
                'original_response': None
            }
        
        except User.DoesNotExist:
            logger.error(f"User {user_id} not found")
            return {
                'success': False,
                'response': None,
                'error': f'User not found'
            }
        except Exception as e:
            logger.error(f"OpenAI Error for user {user_id}: {str(e)}")
            return {
                'success': False,
                'response': None,
                'error': str(e)
            }
